#!/usr/bin/env bash

#current_branch=$(git symbolic-ref --short head)
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $current_branch != "main" ]]; then
  exit 0
fi
echo "Running pre-push hook on $current_branch branch"
make all
# $? stores exit value of the last command
if [[ $? != 0 ]]; then
 echo "Tests must pass before push to main!"
 exit 1
fi

exit 0
